-- Generated by nwg-displays on 2026-10-03 at 14:10:46. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@180.0",
    position = "2041x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@75.0",
    position = "121x360",
    scale = 1,
    vrr = 0
})
